
#Global Worldgen Settings
[worldgen]
	#Set this to false to disable all worldgen [true / false, default: true]
	enableWorldgen = true

#Basalt Generation
[basalt]
	#Generate basalt in the world [true / false]
	basaltGeneration = true
	#Size of basalt pockets [0-100, default: 33]
	#Range: 0 ~ 100
	basaltSize = 56
	#Amount of of basalt pocket being generated [0-20, default: 5]
	#Range: 0 ~ 20
	basaltChance = 5
	#Minimal height for basalt pocket generation [-63~318, default: -56]
	#Range: -63 ~ 319
	basaltMinHeight = -56
	#Maximal height for basalt pocket generation, must be higher than minimal height [-63~319, default: 8]
	#Range: -64 ~ 384
	basaltMaxHeight = 8

#Slate Generation
[slate]
	#Generate slate in the world [true / false]
	slateGeneration = true
	#Size of slate pockets [0-100, default: 48]
	#Range: 0 ~ 100
	slateSize = 48
	#Amount of of slate pocket being generated [0-20, default: 3]
	#Range: 0 ~ 20
	slateChance = 3
	#Minimal height for slate pocket generation [-63~318, default: 32]
	#Range: -63 ~ 318
	slateMinHeight = 32
	#Maximal height for slate pocket generation, must be higher than minimal height [-63~319, default: 128]
	#Range: -63 ~ 319
	slateMaxHeight = 128

#Marble Generation
[marble]
	#Generate marble in the world [true / false]
	marbleGeneration = true
	#Size of marble pockets [0-100, default: 32]
	#Range: 0 ~ 100
	marbleSize = 32
	#Amount of of marble pocket being generated [0-20, default: 3]
	#Range: 0 ~ 20
	marbleChance = 3
	#Minimal height for marble pocket generation [-63~318, default: 64]
	#Range: -63 ~ 318
	marbleMinHeight = 64
	#Maximal height for marble pocket generation, must be higher than minimal height [-63~319, default: 196]
	#Range: -63 ~ 319
	marbleMaxHeight = 196

#Gneiss Generation
[gneiss]
	#Generate gneiss in the world [true / false]
	gneissGeneration = true
	#Size of gneiss pockets [0-100, default: 16]
	#Range: 0 ~ 100
	gneissSize = 32
	#Amount of of gneiss pocket being generated [0-20, default: 2]
	#Range: 0 ~ 20
	gneissChance = 2
	#Minimal height for gneiss pocket generation [-63~318, default: 16]
	#Range: -63 ~ 318
	gneissMinHeight = 16
	#Maximal height for gneiss pocket generation, must be higher than minimal height [-63~319, default: 64]
	#Range: -63 ~ 319
	gneissMaxHeight = 64

#Jade Generation
[jade]
	#Generate jade in the world [true / false]
	jadeGeneration = true
	#Size of jade pockets [0-100, default: 15]
	#Range: 0 ~ 100
	jadeSize = 16
	#Amount of of jade pocket being generated [0-20, default: 5]
	#Range: 0 ~ 20
	jadeChance = 3
	#Minimal height for jade pocket generation, [-63~318, default: 50]
	#Range: -63 ~ 318
	jadeMinHeight = 72
	#Maximal height for jade pocket generation, must be higher than minimal height [-63~319, default: 100]
	#Range: -63 ~ 319
	jadeMaxHeight = 192

#Larvikite Generation
[larvikite]
	#Generate larvikite in the world [true / false]
	larvikiteGeneration = true
	#Size of larvikite pockets [0-100, default: 15]
	#Range: 0 ~ 100
	larvikiteSize = 48
	#Amount of of larvikite pocket being generated [0-20, default: 5]
	#Range: 0 ~ 20
	larvikiteChance = 1
	#Minimal height for larvikite pocket generation, [-63~318, default: 50]
	#Range: -63 ~ 318
	larvikiteMinHeight = 48
	#Maximal height for larvikite pocket generation, must be higher than minimal height [-63~319, default: 100]
	#Range: -63 ~ 319
	larvikiteMaxHeight = 72

#Biome Blacklist: list here the biomes you do not want a rock to be generated in (syntax: "modid:biome". Examples: "minecraft:plains", "biomesoplenty:meadow"...). Note: you can replace the default values, rocks only generate where stone is. They never generate in the Nether or the End.
[blacklist]
	#Set to true to switch basalt blacklist to whitelist mode [true / false]
	basaltWhitelist = false
	#List of blacklisted biomes for basalt generation
	basaltBiomeBlacklist = ["minecraft:nether_wastes", "minecraft:soul_sand_valley", "minecraft:basalt_deltas", "minecraft:crimson_forest", "minecraft:warped_forest", "minecraft:the_end", "minecraft:end_barrens", "minecraft:end_midlands", "minecraft:end_highlands", "minecraft:small_end_islands", "minecraft:the_void"]
	#Set to true to switch slate blacklist to whitelist mode [true / false]
	slateWhitelist = false
	#List of blacklisted biomes for slate generation
	slateBiomeBlacklist = ["minecraft:nether_wastes", "minecraft:soul_sand_valley", "minecraft:basalt_deltas", "minecraft:crimson_forest", "minecraft:warped_forest", "minecraft:the_end", "minecraft:end_barrens", "minecraft:end_midlands", "minecraft:end_highlands", "minecraft:small_end_islands", "minecraft:the_void"]
	#Set to true to switch marble blacklist to whitelist mode [true / false]
	marbleWhitelist = false
	#List of blacklisted biomes for marble generation
	marbleBiomeBlacklist = ["minecraft:nether_wastes", "minecraft:soul_sand_valley", "minecraft:basalt_deltas", "minecraft:crimson_forest", "minecraft:warped_forest", "minecraft:the_end", "minecraft:end_barrens", "minecraft:end_midlands", "minecraft:end_highlands", "minecraft:small_end_islands", "minecraft:the_void"]
	#Set to true to switch gneiss blacklist to whitelist mode [true / false]
	gneissWhitelist = false
	#List of blacklisted biomes for gneiss generation
	gneissBiomeBlacklist = ["minecraft:nether_wastes", "minecraft:soul_sand_valley", "minecraft:basalt_deltas", "minecraft:crimson_forest", "minecraft:warped_forest", "minecraft:the_end", "minecraft:end_barrens", "minecraft:end_midlands", "minecraft:end_highlands", "minecraft:small_end_islands", "minecraft:the_void"]
	#Set to true to switch jade blacklist to whitelist mode [true / false]
	jadeWhitelist = false
	#List of blacklisted biomes for jade generation
	jadeBiomeBlacklist = ["minecraft:nether_wastes", "minecraft:soul_sand_valley", "minecraft:basalt_deltas", "minecraft:crimson_forest", "minecraft:warped_forest", "minecraft:the_end", "minecraft:end_barrens", "minecraft:end_midlands", "minecraft:end_highlands", "minecraft:small_end_islands", "minecraft:the_void"]
	#Set to true to switch larvikite blacklist to whitelist mode [true / false] (default is true for larvikite)
	larvikiteWhitelist = true
	#List of blacklisted biomes for larvikite generation (note, by default larvikite only generates in those biomes)
	larvikiteBiomeBlacklist = ["minecraft:cold_ocean", "minecraft:frozen_ocean", "minecraft:frozen_peaks", "minecraft:frozen_river", "minecraft:grove", "minecraft:ice_spikes", "minecraft:jagged_peaks", "minecraft:old_growth_pine_taiga", "minecraft:old_growth_spruce_taiga", "minecraft:snowy_beach", "minecraft:snowy_plains", "minecraft:snowy_slopes", "minecraft:snowy_taiga", "minecraft:stony_peaks", "minecraft:taiga", "minecraft:windswept_forest", "minecraft:windswept_gravelly_hills", "minecraft:windswept_hills"]

