
[general]
	#Set this to true to enable omnigenders, meaning the gender of the animal is irrelevant to who can fall pregnant, lay eggs, milk or sire young. False results in gendered animals. Visually nothing changes.
	"Allow Omnigenders:" = false
	"Allow feeding to age/grow animals:" = false
	#Allowed Values: RAVENOUS, MORE_HUNGRY, STANDARD, LESS_HUNGRY, NEVER_HUNGRY
	"How fast the animals get hungry, Values: RAVENOUS, MORE_HUNGRY, STANDARD, LESS_HUNGRY, NEVER_HUNGRY" = "STANDARD"
	#Range: 0 ~ 100
	"How random the genes should be, 100 is all wildtype animals, 0 is completely random which often results in all white animals:" = 90
	"Animal inventory tabs will be on the top if true and tabs will be on the side if false:" = true
	"Animals will spawn with random biome type" = false
	"Genetic animals are immune to all damage unless attacked with an axe by a player" = false

[Trading]
	#If true leather workers will have extra trades for some Genetic Animal's items
	"Extra leather worker trades" = true
	#If true shepards will have extra trades for some Genetic Animal's items
	"Extra shepard trades" = true
	#If true farmers will have extra trades for some Genetic Animal's items
	"Extra farmer trades" = true
	#If true wandering traders will have extra trades for some Genetic Animal's items
	"Extra wandering traders trades" = true
	#If true wandering traders have a chance to bring chickens to trade
	"Wandering traders sell chickens" = true
	#If true wandering traders have a chance to bring pigs to trade
	"Wandering traders sell pigs" = true
	#If true wandering traders have a chance to bring cows to trade
	"Wandering traders sell cows" = true
	#If true wandering traders have a chance to bring sheep to trade
	"Wandering traders sell sheep" = true
	#If true wandering traders have a chance to bring rabbits to trade
	"Wandering traders sell rabbits" = true
	#If true wandering traders have a chance to bring llamas to trade
	"Wandering traders sell llamas" = true
	#If true wandering traders have a chance to bring mooshrooms to trade
	"Wandering traders sell mooshrooms" = false
	#If true wandering traders have a chance to bring mooblooms to trade
	"Wandering traders sell mooblooms" = false
	#If true wandering traders have a chance to bring turtles to trade
	"Wandering traders sell turtles" = true
	#If true wandering traders have a chance to bring axolotls to trade
	"Wandering traders sell axolotls" = true

[pig]
	#Range: > 5
	"How many ticks it takes for a Pig to give birth, 24000 = 1 Minecraft Day:" = 48000
	#Range: > 1
	"How many ticks it takes for a pig to become an adult, 24000 = 1 Minecraft Day:" = 60000
	"Allow vanilla minecraft Pigs to spawn/exist:" = false
	"Allow Genetic Pigs to continue to spawn/exist:" = true

	[pig."How highly pig spawning is weighted, larger numbers spawn more"]
		#Range: 1 ~ 20
		" Default is 6" = 6

	[pig."The minimum number of pigs you want to find in a group at spawn"]
		#Range: 1 ~ 60
		" Default is 2" = 2

	[pig."The maximum number of pigs you want to find in a group at spawn"]
		#Range: 1 ~ 60
		" Default is 3" = 3

[cow]
	#Range: > 5
	"How many ticks it takes for a Cow to give birth, 24000 = 1 Minecraft Day:" = 48000
	#Range: > 1
	"How many ticks it takes for a cow to become an adult, 24000 = 1 Minecraft Day:" = 84000
	"Allow vanilla minecraft Cows to spawn/exist:" = false
	"Allow Genetic Cows to continue to spawn/exist:" = true

	[cow."How highly cow spawning is weighted, larger numbers spawn more"]
		#Range: 1 ~ 20
		" Default is 8" = 8

	[cow."The minimum number of cows you want to find in a group at spawn"]
		#Range: 1 ~ 60
		" Default is 4" = 4

	[cow."The maximum number of cows you want to find in a group at spawn"]
		#Range: 1 ~ 60
		" Default is 4" = 4

[mooshroom]
	#Range: > 5
	"How many ticks it takes for a Mooshroom to give birth, 24000 = 1 Minecraft Day:" = 48000
	#Range: > 1
	"How many ticks it takes for a Mooshroom to become an adult, 24000 = 1 Minecraft Day:" = 84000
	"Allow vanilla minecraft Mooshrooms to spawn/exist:" = false
	"Allow Genetic Mooshrooms to continue to spawn/exist:" = true

	[mooshroom."How highly Mooshroom spawning is weighted, larger numbers spawn more"]
		#Range: 1 ~ 20
		" Default is 8" = 8

	[mooshroom."The minimum number of Mooshrooms you want to find in a group at spawn"]
		#Range: 1 ~ 60
		" Default is 4" = 4

	[mooshroom."The maximum number of Mooshrooms you want to find in a group at spawn"]
		#Range: 1 ~ 60
		" Default is 4" = 4

[moobloom]
	"Allow Genetic Mooblooms to replace Mooblooms added by other mods" = false
	#Range: > 5
	"How many ticks it takes for a Mooblooms to give birth, 24000 = 1 Minecraft Day:" = 48000
	#Range: > 1
	"How many ticks it takes for a Mooblooms to become an adult, 24000 = 1 Minecraft Day:" = 84000

[llama]
	"Allow vanilla minecraft Llamas to spawn/exist:" = false
	"Allow Genetic Llamas to continue to spawn/exist:" = true
	#Range: > 5
	"How many ticks it takes for a Llama to give birth, 24000 = 1 Minecraft Day:" = 48000
	#Range: > 1
	"How many ticks it takes for a llama to become an adult, 24000 = 1 Minecraft Day:" = 120000

	[llama."How highly llama spawning is weighted, larger numbers spawn more"]
		#Range: 1 ~ 20
		" Default is 4" = 4

	[llama."The minimum number of llamas you want to find in a group at spawn"]
		#Range: 1 ~ 60
		" Default is 2" = 2

	[llama."The maximum number of llamas you want to find in a group at spawn"]
		#Range: 1 ~ 60
		" Default is 3" = 3

[sheep]
	#Range: > 5
	"How many ticks it takes for a Sheep to give birth, 24000 = 1 Minecraft Day:" = 48000
	#Range: > 1
	"How many ticks it takes for a Sheep to become an adult, 24000 = 1 Minecraft Day:" = 72000
	"Allow vanilla minecraft Sheep to spawn/exist:" = false
	"Allow Genetic Sheep to continue to spawn/exist:" = true

	[sheep."How highly Sheep spawning is weighted, larger numbers spawn more"]
		#Range: 1 ~ 20
		" Default is 12" = 12

	[sheep."The minimum number of Sheep you want to find in a group at spawn"]
		#Range: 1 ~ 60
		" Default is 4" = 4

	[sheep."The maximum number of Sheep you want to find in a group at spawn"]
		#Range: 1 ~ 60
		" Default is 4" = 4

[chicken]
	"Allow vanilla minecraft Chickens to spawn/exist:" = false
	"Allow Genetic Chickens to continue to spawn/exist:" = true
	#Range: > 1
	"How many ticks it takes for a Chicken egg to hatch, 24000 = 1 Minecraft Day:" = 24000
	#Range: > 1
	"How many ticks it takes for a Chicken to become an adult, 24000 = 1 Minecraft Day:" = 60000

	[chicken."How highly Chicken spawning is weighted, larger numbers spawn more"]
		#Range: 1 ~ 20
		" Default is 10" = 10

	[chicken."The minimum number of Chicken you want to find in a group at spawn"]
		#Range: 1 ~ 60
		" Default is 4" = 4

	[chicken."The maximum number of Chicken you want to find in a group at spawn"]
		#Range: 1 ~ 60
		" Default is 4" = 4

[rabbit]
	#Range: > 5
	"How many ticks it takes for a Rabbit to give birth, 24000 = 1 Minecraft Day:" = 24000
	#Range: > 1
	"How many ticks it takes for a Rabbit to become an adult, 24000 = 1 Minecraft Day:" = 48000
	"Allow vanilla minecraft Rabbits to spawn/exist:" = false
	"Allow Genetic Rabbits to continue to spawn/exist:" = true

	[rabbit."How highly Rabbit spawning is weighted, larger numbers spawn more"]
		#Range: 1 ~ 20
		" Default is 4" = 4

	[rabbit."The minimum number of Rabbit you want to find in a group at spawn"]
		#Range: 1 ~ 60
		" Default is 2" = 2

	[rabbit."The maximum number of Rabbit you want to find in a group at spawn"]
		#Range: 1 ~ 60
		" Default is 3" = 3

[turtle]
	"Allow vanilla minecraft Turtles to spawn/exist:" = false
	"Allow Genetic Turtles to continue to spawn/exist:" = true
	#Range: > 1
	"How many ticks it takes for a Turtle to become an adult, 24000 = 1 Minecraft Day:" = 120000
	#Range: > 1
	"How many ticks it takes for a Turtle to drop its scute, 24000 = 1 Minecraft Day:" = 24000

	[turtle."How highly Turtle spawning is weighted, larger numbers spawn more"]
		#Range: 1 ~ 20
		" Default is 6" = 6

	[turtle."The minimum number of Turtle you want to find in a group at spawn"]
		#Range: 1 ~ 60
		" Default is 1" = 1

	[turtle."The maximum number of Turtle you want to find in a group at spawn"]
		#Range: 1 ~ 60
		" Default is 5" = 5

[horse]
	#Range: > 5
	"How many ticks it takes for a Horse to give birth, 24000 = 1 Minecraft Day:" = 24000
	#Range: > 1000
	"How many ticks it takes for a Horse to become an adult, 24000 = 1 Minecraft Day:" = 24000
	"Allow vanilla minecraft Horses to spawn/exist:" = false
	"Allow Genetic Horse to continue to spawn/exist:" = true

[axolotl]
	"Allow vanilla minecraft Axolotls to spawn/exist:" = false
	"Allow Genetic Axolotls to continue to spawn/exist:" = true
	#Range: > 1
	"How many ticks it takes for an Axolotl to become an adult, 24000 = 1 Minecraft Day:" = 60000

	[axolotl."How long int ticks it takes an axolotl egg to hatch in temperate biomes"]
		#Range: > 1
		" Default is 24000" = 24000

	[axolotl."How important temperature is to the hatching of axolotl eggs"]

		[axolotl."How important temperature is to the hatching of axolotl eggs"." A value of 0 means they will never hatch unless they are in a temperate or warmer environment"]
			#Range: 0.0 ~ 100.0
			" Currently not used" = 1.0

	[axolotl."How highly Axolotl spawning is weighted, larger numbers spawn more"]
		#Range: 1 ~ 20
		" Default is 10" = 10

	[axolotl."The minimum number of Axolotls you want to find in a group at spawn"]
		#Range: 1 ~ 60
		" Default is 4" = 4

	[axolotl."The maximum number of Axolotls you want to find in a group at spawn"]
		#Range: 1 ~ 60
		" Default is 6" = 6

